[package]
name = "mmft"
version = "0.1.0"
authors = ["Max Brown <max.carter-brown@aru.ac.uk>"]
edition = "2021"
license = "MIT"
description = "A minimal fasta toolkit."
keywords = ["fasta", "tools"]
categories = ["command-line-utilities", "science"]
homepage = "https://github.com/tolkit/mmft"
documentation = "https://github.com/tolkit/mmft"
repository = "https://github.com/tolkit/mmft"

[dependencies]
bio = "1.4.0"
atty = "0.2.14"
thiserror = "1.0.50"
anyhow = "1.0.75"
regex = "1.10.2"
rand = "0.8.5"
flate2 = "1.0.28"
clap = { version = "4.4.8", features = ["cargo"] }
lexical-sort = "0.3.1"
