[package]
name = "mmft"
version = "0.1.0"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "0.41.0"
clap = { version = "3.1.18", features = ["cargo"] }
atty = "0.2"
thiserror = "1.0"
anyhow = "1.0"
regex = "1.5"