[package]
name = "mmft"
version = "0.1.0"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2021"
license = "MIT"
description = "A minimal fasta toolkit."
keywords = ["fasta", "tools"]
categories = ["command-line-utilities", "science"]
homepage = "https://github.com/tolkit/mmft"
documentation = "https://github.com/tolkit/mmft"
repository = "https://github.com/tolkit/mmft"

[dependencies]
bio = "0.41.0"
clap = { version = "3.1.18", features = ["cargo"] }
atty = "0.2"
thiserror = "1.0"
anyhow = "1.0"
regex = "1.5"
rand = "0.8.5"
